import sqlite3

# create a connection
conn = sqlite3.connect('values.db')

# create a table
c = conn.cursor()  # cursor

c.execute("""CREATE TABLE robot (
            date DATE,
            current_logged_user_level TEXT,
            robot_running INTEGER
    )""")

# commit
conn.commit()

# close the connection
conn.close()

"""

bollean ni supported iz strani SQL ligh
robot_playback BOOLEAN,
            robot_energy_saving BOOLEAN,
            product_code INTEGER,
            serial_number INTEGER,
            alarm TEXT,
            alarm_axes INTEGER,
            alarm_code INTEGER,
            alarm_date TEXT,
            alarm_job TEXT,
            alarm_mode TEXT,
            alarm_active BOOLEAN,
            error_active BOOLEAN,
            reset_alarm BOOLEAN,
            reset_error BOOLEAN,
            axis_name_1 TEXT,
            axis_name_2 TEXT,
            axis_name_3 TEXT,
            axis_name_4 TEXT,
            axis_name_5 TEXT,
            axis_name_6 TEXT,
            axis_position_1 INTEGER,
            axis_position_2 INTEGER,
            axis_position_3 INTEGER,
            axis_position_4 INTEGER,
            axis_position_5 INTEGER,
            axis_position_6 INTEGER,
            axis_degree_1 INTEGER,
            axis_degree_2 INTEGER,
            axis_degree_3 INTEGER,
            axis_degree_4 INTEGER,
            axis_degree_5 INTEGER,
            axis_degree_6 INTEGER,
            axis_speed_1 INTEGER,
            axis_speed_2 INTEGER,
            axis_speed_3 INTEGER,
            axis_speed_4 INTEGER,
            axis_speed_5 INTEGER,
            axis_speed_6 INTEGER,
            speed_reducer_design_lifetime_1 INTEGER,
            speed_reducer_design_lifetime_2 INTEGER,
            speed_reducer_design_lifetime_3 INTEGER,
            speed_reducer_design_lifetime_4 INTEGER,
            speed_reducer_design_lifetime_5 INTEGER,
            speed_reducer_design_lifetime_6 INTEGER,
            speed_reducer_remaining_lifetime_1 INTEGER,
            speed_reducer_remaining_lifetime_2 INTEGER,
            speed_reducer_remaining_lifetime_3 INTEGER,
            speed_reducer_remaining_lifetime_4 INTEGER,
            speed_reducer_remaining_lifetime_5 INTEGER,
            speed_reducer_remaining_lifetime_6 INTEGER,
            amplifiers_designed_lifetime_1 INTEGER,
            amplifiers_designed_lifetime_2 INTEGER,
            amplifiers_designed_lifetime_3 INTEGER,
            amplifiers_designed_lifetime_4 INTEGER,
            amplifiers_designed_lifetime_5 INTEGER,
            amplifiers_designed_lifetime_6 INTEGER,
            amplifiers_remaining_lifetime_1 INTEGER,
            amplifiers_remaining_lifetime_2 INTEGER,
            amplifiers_remaining_lifetime_3 INTEGER,
            amplifiers_remaining_lifetime_4 INTEGER,
            amplifiers_remaining_lifetime_5 INTEGER,
            amplifiers_remaining_lifetime_6 INTEGER,
            capacitors_design_lifetime_1 INTEGER,
            capacitors_design_lifetime_2 INTEGER,
            capacitors_design_lifetime_3 INTEGER,
            capacitors_design_lifetime_4 INTEGER,
            capacitors_design_lifetime_5 INTEGER,
            capacitors_design_lifetime_6 INTEGER,
            capacitors_remaining_lifetime_1 INTEGER,
            capacitors_remaining_lifetime_2 INTEGER,
            capacitors_remaining_lifetime_3 INTEGER,
            capacitors_remaining_lifetime_4 INTEGER,
            capacitors_remaining_lifetime_5 INTEGER,
            capacitors_remaining_lifetime_6 INTEGER,
            contactors_design_lifetime_1 INTEGER,
            contactors_design_lifetime_2 INTEGER,
            contactors_design_lifetime_3 INTEGER,
            contactors_design_lifetime_4 INTEGER,
            contactors_design_lifetime_5 INTEGER,
            contactors_design_lifetime_6 INTEGER,
            contactors_remaining_lifetime_1 INTEGER,
            contactors_remaining_lifetime_2 INTEGER,
            contactors_remaining_lifetime_3 INTEGER,
            contactors_remaining_lifetime_4 INTEGER,
            contactors_remaining_lifetime_5 INTEGER,
            contactors_remaining_lifetime_6 INTEGER,
            cps_fan_designed_lifetime INTEGER,
            cps_fan_remaining_lifetime INTEGER,
            controller_box_fan_designed_lifetime INTEGER,
            controller_box_fan_remaining_lifetime INTEGER,
            regenerative_fan_designed_lifetime INTEGER,
            regenerative_box_fan_remaining_lifetime INTEGER,
            manipulator_fan_designed_lifetime INTEGER,
            manipulator_box_fan_remaining_lifetime INTEGER,
            set_job BOOLEAN,
            flange_load BOOLEAN,
            device_manufacturer TEXT,
            device_model TEXT,
            device_moving BOOLEAN,
            total_moving_time INTEGER,
            total_playback_time INTEGER,
            total_servo_on_time INTEGER,
            encoder_temperature_1 INTEGER,
            encoder_temperature_2 INTEGER,
            encoder_temperature_3 INTEGER,
            encoder_temperature_4 INTEGER,
            encoder_temperature_5 INTEGER,
            encoder_temperature_6 INTEGER,
            device_serial_number INTEGER,
            grease_supply_design_lifetime INTEGER,
            grease_supply_remaining_lifetime INTEGER,
            wire_harness_design_lifetime INTEGER,
            wire_harness_remaining_lifetime INTEGER,
            battery_exchange_design_lifetime INTEGER,
            battery_exchange_remaining_lifetime INTEGER,
            overhaul_design_lifetime INTEGER,
            overhaul_remaining_lifetime INTEGER,
            emergency_stop BOOLEAN,
            protective_stop BOOLEAN"""